# Generated by Django 3.0.3 on 2020-03-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urltable',
            name='n0_clicks',
        ),
        migrations.AddField(
            model_name='urltable',
            name='no_clicks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
